"""alter collumns

Revision ID: 09bef188aa9a
Revises: 0a86e02234fa
Create Date: 2022-02-17 13:52:17.632198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bef188aa9a'
down_revision = '0a86e02234fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccine_cards', 'health_unit_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'vaccine_cards', ['cpf'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccine_cards', type_='unique')
    op.alter_column('vaccine_cards', 'health_unit_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
